In [3]:
import pandas as pd

df = pd.read_csv("./Data/Netflix Dataset.csv")

df.head()

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,07:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7789 entries, 0 to 7788
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Show_Id       7789 non-null   object
 1   Category      7789 non-null   object
 2   Title         7789 non-null   object
 3   Director      5401 non-null   object
 4   Cast          7071 non-null   object
 5   Country       7282 non-null   object
 6   Release_Date  7779 non-null   object
 7   Rating        7782 non-null   object
 8   Duration      7789 non-null   object
 9   Type          7789 non-null   object
 10  Description   7789 non-null   object
dtypes: object(11)
memory usage: 669.5+ KB

In [5]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 7789
Columns : 11

In [6]:
df.isnull().sum()

Show_Id            0
Category           0
Title              0
Director        2388
Cast             718
Country          507
Release_Date      10
Rating             7
Duration           0
Type               0
Description        0
dtype: int64

In [7]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 2

In [8]:
df.drop_duplicates(inplace=True)

print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [9]:
df["Release_Date"] = pd.to_datetime(
    df["Release_Date"],
    errors="coerce"
)

In [10]:
df.dtypes

Show_Id                 object
Category                object
Title                   object
Director                object
Cast                    object
Country                 object
Release_Date    datetime64[ns]
Rating                  object
Duration                object
Type                    object
Description             object
dtype: object

In [11]:
df["Director"] = df["Director"].fillna("Unknown")

df["Cast"] = df["Cast"].fillna("Unknown")

df["Country"] = df["Country"].fillna("Unknown")

df["Rating"] = df["Rating"].fillna("Unknown")

In [12]:
df = df.dropna(subset=["Release_Date"])

In [13]:
df.isnull().sum()

Show_Id         0
Category        0
Title           0
Director        0
Cast            0
Country         0
Release_Date    0
Rating          0
Duration        0
Type            0
Description     0
dtype: int64

In [14]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

Show_Id: 7689
Category: 2
Title: 7689
Director: 4047
Cast: 6745
Country: 678
Release_Date: 1497
Rating: 15
Duration: 216
Type: 487
Description: 7671

In [15]:
df.describe(include="all")

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
count,7689,7689,7689,7689,7689,7689,7689,7689,7689,7689,7689
unique,7689,2,7689,4047,6745,678,NaN,15,216,487,7671
top,s1,Movie,3%,Unknown,Unknown,United States,NaN,TV-MA,1 Season,Documentaries,Multiple women report their husbands as missin...
freq,1,5377,1,2295,710,2515,NaN,2839,1606,334,3
mean,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-07 20:44:06.273897728,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,2008-01-01 00:00:00,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,2018-02-06 00:00:00,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2019-03-15 00:00:00,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2020-01-25 00:00:00,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,2021-01-16 00:00:00,NaN,NaN,NaN,NaN

In [16]:
df.to_csv("./Data/cleaned_netflix.csv", index=False)